### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by sarmishra** [amarlearning/Finger-Detection-and-Tracking#10]
Thank you bro  @amarlearning  for the code and tutorials: 
Getting error while running FingerDetection.py file --

    _, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

it is require any dependency file to run or why it is not working in my laptop.

**Comment by amarlearning** [comment]
@sarmishra Thanks!

Can you confirm that you are using OpenCV version 3.4.5.20 as mentioned in the [requirement.txt](https://github.com/amarlearning/Finger-Detection-and-Tracking/blob/master/requirement.txt) file

**Comment by amarlearning** [comment]
Closing this issue due to no response, please feel free to reopen.
