### ISSUE TITLE
Can you give me some steps of instructions how to have it running on Ubuntu?

### ISSUE THREAD

**Issue by nikkolasedi** [amarlearning/Finger-Detection-and-Tracking#11]
I just run the FingerDetection.py on the Terminal with these commands:

phyton FingerDetection.py
chmod +x FingerDetection.py
./FingerDetection.py 

and got this as result:

import-im6.q16: not authorized `cv2' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `np' @ error/constitute.c/WriteImage/1037.
./FingerDetection.py: line 4: hand_hist: command not found
./FingerDetection.py: line 5: traverse_point: command not found
./FingerDetection.py: line 6: total_rectangle: command not found
./FingerDetection.py: line 7: hand_rect_one_x: command not found
./FingerDetection.py: line 8: hand_rect_one_y: command not found
./FingerDetection.py: line 10: hand_rect_two_x: command not found
./FingerDetection.py: line 11: hand_rect_two_y: command not found
./FingerDetection.py: line 14: syntax error near unexpected token `('
./FingerDetection.py: line 14: `def rescale_frame(frame, wpercent=130, hpercent=130):'

**Comment by amarlearning** [comment]
After cloning the project, go inside the project directory and run this command `pip install -r requirements.txt`

**Comment by nikkolasedi** [comment]
I've done it and what should I do to run the programm?

**Comment by amarlearning** [comment]
If you are inside the repository, go inside the folder `Finger Detection and Tracking` and run the command `python FingerDetection.py`

**Comment by nikkolasedi** [comment]
Thanks it works but still needs some improvement, because it only works on the plain background.
