### ISSUE TITLE
Program goes to not responding on pressing Z key

### ISSUE THREAD

**Issue by dhruvaop** [amarlearning/Finger-Detection-and-Tracking#17]
when I press the key z it terminates automatically

**Comment by amarlearning** [comment]
@dhruvaop For me, the code is working fine, can you share more details about the error stack.

And can you confirm that you have downloaded the dependency using the requirements.txt file?

**Comment by amarlearning** [comment]
Please use python 3.8 and install other dependencies from the `requirements.txt` file.
