### ISSUE TITLE
@dhruvaop For me, the code is working fine, can you share more details about the error stack.

### ISSUE THREAD

**Issue by dhruvaop** [amarlearning/Finger-Detection-and-Tracking#19]
@dhruvaop For me, the code is working fine, can you share more details about the error stack.

And can you confirm that you have downloaded the dependency using the requirements.txt file?

_Originally posted by @amarlearning in https://github.com/amarlearning/Finger-Detection-and-Tracking/issues/17#issuecomment-912662595_

Yes, I have downloaded from requirements.txt but as soon as I press z it terminates 
I think the version is different that I am using

**Comment by dhruvaop** [comment]
version problem

**Comment by amarlearning** [comment]
Please use python 3.8 and install other dependencies from the `requirements.txt` file.

You don't have to open a new issue, you can post your queries in the existing issue.
