### ISSUE TITLE
Unable to detect and track finger tip

### ISSUE THREAD

**Issue by manish-singla** [amarlearning/Finger-Detection-and-Tracking#7]
Hey,
Firstly there was an error in FingerDetction.py  bold line below:
def contours(hist_mask_image):
    gray_hist_mask_image = cv2.cvtColor(hist_mask_image, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(gray_hist_mask_image, 0, 255, 0)
    **__, cont, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)**
    return cont
The error was findContours function return 2 arguments but code is expecting 3 values. Hence I modifed the code as
 **cont, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)**

No code is working fine, but finger is not detected. Is this due to above change or lightening/other factors?

**Comment by manish-singla** [comment]
I assume this is a more of version issue.
http://answers.opencv.org/question/138405/confused-even-after-studying-contours-need-more-than-2-values-to-unpack/ 
Have you got any updates for the code.

**Comment by amarlearning** [comment]
Resolved in 7b458dff32f0a9f621d893f8098989f1f6e59f27
